version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - 3306:3306
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 3000:3000
# docker run -p 3000:3000 back
